-- Run this after the base migration in Supabase SQL Editor.
-- It is safe to rerun: categories and destinations upsert on unique slugs.

INSERT INTO public.categories (name, slug, description, icon, item_count)
VALUES
  ('Trekking', 'trekking', 'Multi-day trails, scenic routes, and iconic long-distance hikes.', 'mountain', 0),
  ('Mountaineering', 'mountaineering', 'High-altitude routes, glacier travel, and summit objectives.', 'mountain-snow', 0),
  ('Camping', 'camping', 'Camp-based outdoor adventures from alpine meadows to remote valleys.', 'tent', 0),
  ('Water Sports', 'water-sports', 'Lakes, rivers, paddling routes, and water-focused escapes.', 'waves', 0),
  ('Rock Climbing', 'rock-climbing', 'Crags, alpine walls, and classic climbing zones.', 'flame', 0),
  ('Mountain Biking', 'mountain-biking', 'Singletrack, bikepacking routes, and high-country descents.', 'bike', 0)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  icon = EXCLUDED.icon;

WITH category_map AS (
  SELECT id, slug FROM public.categories
)
INSERT INTO public.destinations (
  title,
  slug,
  description,
  location,
  country,
  continent,
  latitude,
  longitude,
  difficulty,
  duration,
  distance_km,
  elevation_m,
  best_season,
  image_url,
  gallery,
  tags,
  category_id,
  avg_rating,
  review_count,
  is_featured,
  is_trending,
  source_url
)
VALUES
  (
    'Everest Base Camp Trek',
    'everest-base-camp-trek',
    'Nepal''s classic high-altitude trek through the Khumbu with Sherpa villages, suspension bridges, and close views of Everest.',
    'Khumbu Region',
    'Nepal',
    'Asia',
    28.0043,
    86.8571,
    'Challenging',
    '12-14 days',
    130,
    5364,
    'March-May, October-November',
    NULL,
    ARRAY[]::TEXT[],
    ARRAY['himalaya', 'altitude', 'base-camp', 'teahouse'],
    (SELECT id FROM category_map WHERE slug = 'trekking'),
    4.9,
    186,
    true,
    true,
    'https://en.wikipedia.org/wiki/Everest_Base_Camp'
  ),
  (
    'Annapurna Circuit',
    'annapurna-circuit',
    'A legendary Himalayan circuit crossing deep valleys, high passes, and varied landscapes around the Annapurna massif.',
    'Annapurna Region',
    'Nepal',
    'Asia',
    28.5970,
    83.9311,
    'Advanced',
    '14-18 days',
    160,
    5416,
    'March-May, September-November',
    NULL,
    ARRAY[]::TEXT[],
    ARRAY['himalaya', 'thorong-la', 'teahouse', 'circuit'],
    (SELECT id FROM category_map WHERE slug = 'trekking'),
    4.8,
    142,
    true,
    true,
    'https://en.wikipedia.org/wiki/Annapurna_Circuit'
  ),
  (
    'Tour du Mont Blanc',
    'tour-du-mont-blanc',
    'An iconic alpine circuit through France, Italy, and Switzerland with dramatic glaciers, passes, and mountain villages.',
    'Mont Blanc Massif',
    'France',
    'Europe',
    45.9237,
    6.8694,
    'Moderate',
    '10-12 days',
    170,
    2665,
    'June-September',
    NULL,
    ARRAY[]::TEXT[],
    ARRAY['alps', 'hut-to-hut', 'cross-border', 'glacier-views'],
    (SELECT id FROM category_map WHERE slug = 'trekking'),
    4.7,
    98,
    true,
    false,
    'https://en.wikipedia.org/wiki/Tour_du_Mont_Blanc'
  ),
  (
    'Kilimanjaro Marangu Route',
    'kilimanjaro-marangu-route',
    'A hut-supported ascent of Africa''s highest peak with equatorial forest, moorland, and a summit push to Uhuru Peak.',
    'Kilimanjaro National Park',
    'Tanzania',
    'Africa',
    -3.0758,
    37.3533,
    'Advanced',
    '5-6 days',
    72,
    5895,
    'January-March, June-October',
    NULL,
    ARRAY[]::TEXT[],
    ARRAY['summit', 'africa', 'hut-route', 'volcano'],
    (SELECT id FROM category_map WHERE slug = 'mountaineering'),
    4.6,
    77,
    false,
    true,
    'https://en.wikipedia.org/wiki/Mount_Kilimanjaro'
  ),
  (
    'Aconcagua Normal Route',
    'aconcagua-normal-route',
    'A high-altitude expedition route to the highest mountain in the Americas, emphasizing acclimatization and weather windows.',
    'Mendoza Province',
    'Argentina',
    'South America',
    -32.6532,
    -70.0109,
    'Expert',
    '16-20 days',
    60,
    6961,
    'December-February',
    NULL,
    ARRAY[]::TEXT[],
    ARRAY['seven-summits', 'expedition', 'altitude', 'andes'],
    (SELECT id FROM category_map WHERE slug = 'mountaineering'),
    4.8,
    51,
    false,
    true,
    'https://en.wikipedia.org/wiki/Aconcagua'
  ),
  (
    'Patagonia W Trek',
    'patagonia-w-trek',
    'A hut-and-camp route through Torres del Paine featuring granite towers, glacial lakes, and fierce Patagonian weather.',
    'Torres del Paine',
    'Chile',
    'South America',
    -50.9423,
    -73.4068,
    'Moderate',
    '4-5 days',
    80,
    900,
    'November-March',
    NULL,
    ARRAY[]::TEXT[],
    ARRAY['patagonia', 'glacier', 'camping', 'national-park'],
    (SELECT id FROM category_map WHERE slug = 'camping'),
    4.8,
    123,
    true,
    true,
    'https://en.wikipedia.org/wiki/Torres_del_Paine_National_Park'
  ),
  (
    'Milford Track',
    'milford-track',
    'One of New Zealand''s classic Great Walks with rainforest, alpine passes, and organized backcountry hut stops.',
    'Fiordland National Park',
    'New Zealand',
    'Oceania',
    -44.7652,
    167.8380,
    'Moderate',
    '4 days',
    53.5,
    1154,
    'October-April',
    NULL,
    ARRAY[]::TEXT[],
    ARRAY['great-walk', 'hut', 'waterfalls', 'fiordland'],
    (SELECT id FROM category_map WHERE slug = 'camping'),
    4.7,
    64,
    false,
    false,
    'https://en.wikipedia.org/wiki/Milford_Track'
  ),
  (
    'Lake Atitlan Kayak Circuit',
    'lake-atitlan-kayak-circuit',
    'A scenic multi-stop paddle journey across volcanic shores, local villages, and highland waters of Lake Atitlan.',
    'Lake Atitlan',
    'Guatemala',
    'North America',
    14.6900,
    -91.2029,
    'Easy',
    '1-2 days',
    24,
    1562,
    'November-April',
    NULL,
    ARRAY[]::TEXT[],
    ARRAY['kayak', 'lake', 'volcano', 'paddle'],
    (SELECT id FROM category_map WHERE slug = 'water-sports'),
    4.5,
    21,
    false,
    false,
    'https://en.wikipedia.org/wiki/Lake_Atitl%C3%A1n'
  ),
  (
    'El Potrero Chico Sport Climbing',
    'el-potrero-chico-sport-climbing',
    'A world-class limestone climbing area with multi-pitch sport routes and winter-friendly conditions.',
    'Nuevo Leon',
    'Mexico',
    'North America',
    25.9522,
    -100.4775,
    'Advanced',
    '3-7 days',
    18,
    700,
    'November-March',
    NULL,
    ARRAY[]::TEXT[],
    ARRAY['sport-climbing', 'limestone', 'multi-pitch', 'winter'],
    (SELECT id FROM category_map WHERE slug = 'rock-climbing'),
    4.6,
    38,
    false,
    false,
    'https://en.wikipedia.org/wiki/El_Potrero_Chico'
  ),
  (
    'Moab Whole Enchilada',
    'moab-whole-enchilada',
    'A famous mountain bike descent from alpine forest to desert slickrock with huge elevation loss and varied terrain.',
    'Moab, Utah',
    'United States',
    'North America',
    38.5733,
    -109.5498,
    'Challenging',
    '1 day',
    43,
    2400,
    'May-June, September-October',
    NULL,
    ARRAY[]::TEXT[],
    ARRAY['singletrack', 'desert', 'bike', 'downhill'],
    (SELECT id FROM category_map WHERE slug = 'mountain-biking'),
    4.9,
    56,
    true,
    true,
    'https://en.wikipedia.org/wiki/Moab,_Utah'
  )
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  location = EXCLUDED.location,
  country = EXCLUDED.country,
  continent = EXCLUDED.continent,
  latitude = EXCLUDED.latitude,
  longitude = EXCLUDED.longitude,
  difficulty = EXCLUDED.difficulty,
  duration = EXCLUDED.duration,
  distance_km = EXCLUDED.distance_km,
  elevation_m = EXCLUDED.elevation_m,
  best_season = EXCLUDED.best_season,
  image_url = EXCLUDED.image_url,
  gallery = EXCLUDED.gallery,
  tags = EXCLUDED.tags,
  category_id = EXCLUDED.category_id,
  avg_rating = EXCLUDED.avg_rating,
  review_count = EXCLUDED.review_count,
  is_featured = EXCLUDED.is_featured,
  is_trending = EXCLUDED.is_trending,
  source_url = EXCLUDED.source_url,
  updated_at = now();

UPDATE public.categories c
SET item_count = counts.destination_count
FROM (
  SELECT category_id, COUNT(*)::INTEGER AS destination_count
  FROM public.destinations
  WHERE category_id IS NOT NULL
  GROUP BY category_id
) counts
WHERE counts.category_id = c.id;