-- Dravik app frontend seed data (trails, guides, countries).
-- Run AFTER the migration 20260316094500_drivik_app_frontend_tables.sql in the Supabase SQL editor.
-- Safe to rerun: uses ON CONFLICT (id) DO NOTHING.

-- ========================= TRAILS =========================
insert into public.trails (id, name, location, country, difficulty, distance, elevation, duration, rating, lat, lng, description, image, best_season, highlights) values
('1','Annapurna Base Camp','Pokhara, Nepal','Nepal','hard',110,4130,'10-12 days',4.8,28.53,83.87,'Classic Himalayan trek through diverse landscapes to the amphitheater of Annapurna. Pass through lush rhododendron forests, terraced rice paddies, and traditional Gurung villages.','🏔️','Oct-Nov, Mar-Apr','["Annapurna Sanctuary","Hot springs at Jhinu","Machapuchare views","Gurung villages"]'),
('2','Everest Base Camp','Solukhumbu, Nepal','Nepal','hard',130,5364,'12-14 days',4.9,2-- Dravik app frontend seed data (trails, guides, countries).
-- Run AFTER the migration 2lt-- Run AFTER the migration 20260316094500_drivik_app_frontends-- Safe to rerun: uses ON CONFLICT (id) DO NOTHING.

-- ========================= TRAILS ==========",
-- ========================= TRAILS =============u',insert into public.trails (id, name, location, country, difft ('1','Annapurna Base Camp','Pokhara, Nepal','Nepal','hard',110,4130,'10-12 days',4.8,28.53,83.87,'Classic Himalayan trek through diverse landscapes to the amphitheater,'('2','Everest Base Camp','Solukhumbu, Nepal','Nepal','hard',130,5364,'12-14 days',4.9,2-- Dravik app frontend seed data (trails, guides, countries).
-- Run AFTER the migration 2lt-- Run AFTER the migration 20260316094500_drivik_app_frontends-- Safe to rerun: uses ON CONFLICT (id) DO NOTHING.

-- ========================= TRAILS ==========",
-- ========================= TRAILS =============u',i",-- Run AFTER the migration 2lt-- Run AFTER the migration 20260316094500_drivik_app_frontends-- Safe to rerun: uses ON CONFLICT (id) DO NOTHING.

--8,
-- ========================= TRAILS ==========",
-- ========================= TRAILS =============u',insert into public.trails (id','Jun-Aug','[-- ========================= TRAILS ===========s"-- Run AFTER the migration 2lt-- Run AFTER the migration 20260316094500_drivik_app_frontends-- Safe to rerun: uses ON CONFLICT (id) DO NOTHING.

-- ========================= TRAILS ==========",
-- ========================= TRAILS =============u',i",-- Run AFTER the migration 2lt-- Run AFTER the migration 20260316094500_drivik_app_frontendsones","Sunrise above the clouds"]'),
('7','W Trek','Torres del Paine, Chile','Chile','moder
-- ========================= TRAILS ==========",
-- ========================= TRAILS =============u',i",-- Run AFTER the migration 2lt-- Run ,'[-- ========================= TRAILS ===========y"
--8,
-- ========================= TRAILS ==========",
-- ========================= TRAILS =============u',insert into public.trails (id','Jun-Aug','[-- ========================= TRAILS ===========edr-- ',-- ========================= TRAILS ===========",
-- ========================= TRAILS ==========",
-- ========================= TRAILS =============u',i",-- Run AFTER the migration 2lt-- Run AFTER the migration 20260316094500_drivik_app_frontendsones","Sunrise above the clouds"]'),
('7','W Trek','Torres del Paine, Chile','Chile','modTre-- ========================= TRAILS ===========kn('7','W Trek','Torres del Paine, Chile','Chile','moder
-- ========================= TRAILS ==========",
-- ========================= TRAILS =============u',i",-- Run AFTER the migratov-- ========================= TRAILS ==========",
-- =qu-- ========================= TRAILS ===========:"--8,
-- ========================= TRAILS ==========",
-- ========================= TRAILS =============u',insert into public.trails (id','Jun-A:"-- en-- ========================= TRAILS ===========in-- ========================= TRAILS ==========",
-- ========================= TRAILS =============u',i",-- Run AFTER the migration 2lt-- Run AFTER the migration 20260316094500_drivik_app_frontendsonpa-- ========================= TRAILS ===========Wi('7','W Trek','Torres del Paine, Chile','Chile','modTre-- ========================= TRAILS ===========kn('7','W Trek','Torres del Paine, Chile','Chile','moder
-- ====================t -- ========================= TRAILS ==========",
-- ========================= TRAILS =============u',i",-- Run AFTER the migratov-- =========================nj-- ========================= TRAILS ===========ti-- =qu-- ========================= TRAILS ===========:"--8,
-- ========================= TRAILter aid. Know when to evacuate vs. -- ========================= TRAILS ==========",
-- ======nd-- ========================= TRAILS ===========me-- ========================= TRAILS =============u',i",-- Run AFTER the migration 2lt-- Run AFTER the migration 20260316094500_drivik_app_frontendsonpa-- ========================= TRAILS =====??-- ====================t -- ========================= TRAILS ==========",
-- ========================= TRAILS =============u',i",-- Run AFTER the migratov-- =========================nj-- ========================= TRAILS ===========ti-- =qu-- ========================= TRAILS ===========:"--8,
-- ========================= TRAILter aid. Know when to evacuateti-- ========================= TRAILS =============u',i",-- Run AFTER the  c-- ========================= TRAILter aid. Know when to evacuate vs. -- ========================= TRAILS ==========",
-- ======nd-- ========================= TRAILS ===========me-- ===============rule of threes: 3 minut-- ======nd-- ========================= TRAILS ===========me-- ========================= TRAILS =============u',i",-"b-- ========================= TRAILS =============u',i",-- Run AFTER the migratov-- =========================nj-- ========================= TRAILS ===========ti-- =qu-- ========================= TRAILS ===========:"--8,
-- ========================= TRAILter aid. Know when to evacuateti-- ========================= TRAILS =====lt-- ========================= TRAILter aid. Know when to evacuateti-- ========================= TRAILS =============u',i",-- Run AFTER the  c-- ========================= TRAILter aid. Know when to evacuate vs. -- =====,'-- ======nd-- ========================= TRAILS ===========me-- ===============rule of threes: 3 minut-- ======nd-- ========================= TRAILS ===========me-- ========================= TRAILS =============u',i",-"b-- ========================= TRAILS =on-- ========================= TRAILter aid. Know when to evacuateti-- ========================= TRAILS =====lt-- ========================= TRAILter aid. Know when to evacuateti-- ========================= TRAILS =============u',i",-- Run AFTER the  c-- ========================= TRAILter aid. Know when to evacuate vs. -- =====,'-- ======nd-- ========================= TRAILS ===========me-- ===============rule of threes: 3 minut-- ====imbus warns of storms, lenticular clouds indicate high winds, and cirrus clouds often precede fronts."},{"title":"Wind Patterns","body":"Valley breezes, katabatic winds, and frontal winds all tell different stories about incoming weather."},{"title":"Pressure Changes","body":"Falling pressure indicates incoming storms. A barometric altimeter can double as a weather predictor."}]'),
('7','Leave No Trace Principles','General','Seven principles for minimizing your environmental impact on the trail.','6 min','Beginner','🌿','## Leave No Trace\n\nProtecting wild spaces ensures they remain for future generations.','[{"title":"Plan Ahead","body":"Research regulations, prepare for weather, and plan to minimize waste."},{"title":"Travel on Durable Surfaces","body":"Stick to established trails, camp on designated sites, and avoid fragile ecosystems."},{"title":"Dispose of Waste Properly","body":"Pack out everything you pack in. Use catholes for human waste 200 feet from water."}]'),
('8','Photography on the Trail','Ski('7','Leave No Trace Principles','General','Seven principles for minimizing your environmental impact on the trail.','6 min','Beginner','🌿','## Leave No Trace\n\nProtecting wild spaces ensures they remain for future generations.','[{"title":"Plan Ahead","body":"Research regulations, prepare for weather, and plan to minimize waste."},{"title":"Travel on Durable Surfaces","bodyt,('8','Photography on the Trail','Ski('7','Leave No Trace Principles','General','Seven principles for minimizing your environmental impact on the trail.','6 min','Beginner','🌿','## Leave No Trace\n\nProtecting wild spaces ensures they remain for future generations.','[{"title":"Plan Ahead","body":"Research regulations, prepare for weather, and plan to minimize waste."},{"title":"Travel on Durable Surfaces","bodyt,('8','Photography on the Trail','Ski('7','Leave No Trace Principles','General','Seven principles for minimizing your environmental impact on the trail.','6 min','Beginner','🌿','## L,4.2,'Oct-Nov, Mar-Apr','Subtropical to Alpine','100','Home to 8 of the world''s 14 highest peaks, Nepal is the ultimate trekking destination.','🇳🇵','["Everest Base Camp","Annapurna Circuit","Langtang Valley","Manaslu Circuit"]'),
('2','Peru','PE','Lima','South America',33715000,'["Spanish","Quechua"]','PEN','UTC-5',false,3.8,'May-Sep','Tropical to Alpine','105','Ancient Inca trails, Andean peaks, and Amazon rainforests offer diverse trekking.','🇵🇪','["Inca Trail","Salkantay Trek","Colca Canyon","Huayhuash Circuit"]'),
('3','France','FR','Paris','Western Europe',67390000,'["French"]','EUR','UTC+1',false,4.5,'Jun-Sep','Temperate to Alpine','112','From Alpine summits to Mediterranean coastlines, France offers world-class long-distance trails.','🇫🇷','["Tour du Mont Blanc","GR20 Corsica","GR10 Pyrenees","Vercors Traversée"]'),
('4','Iceland','IS','Reykjavik','Northern Europe',376000,'["Icelandic"]','ISK','UTC+0',false,4.8,'Jun-Aug','Subarctic','112','Volcanic landscapes, glaciers, and geothermal ('2','Peru','PE','Lima','South America',33715000,'["Spanish","Quechua"]','PEN','UTC-5',false,3.8,'May-Sep','Tropical to Alpine','105','Ancient Inca trails, Andean peaks, and Amazon rainforests offer diverse trekking.','🇵🇪','["Ian('3','France','FR','Paris','Western Europe',67390000,'["French"]','EUR','UTC+1',false,4.5,'Jun-Sep','Temperate to Alpine','112','From Alpine summits to Mediterranean coastlines, France offers world-class long-distance trails.','🇫🇷','["Tour du Mont Blanc","GR20 Corsica","GR10 Pyrenees",CLP','UT('4','Iceland','IS','Reykjavik','Northern Europe',376000,'["Icelandic"]','ISK','UTC+0',false,4.8,'Jun-Aug','Subarctic','112','Volcanic landscapes, glaciers, and geothermal ('2','Peru','PE','Lima','South America',33715000,'["Spanish","Quechua"]','PEN','UTC-5',false,3.8,'May-Sep','Tropical to Alpine','105',UR','UTC+1',false,4.6,'Apr-Jun, Sep-Oct','Mediterranean to Oceanic','112','The Camino de Santiago and rugged Pyrenees make Spain a pilgrim''s and trekker''s paradise.','🇪🇸','["Camino de Santiago","GR11 Pyrenees","Picos de Europa","Sierra Nevada"]'),
('8','New Zealand','NZ','Wellington','Oceania',5123000,'["English","Māori"]','NZD','UTC+12',false,4.7,'Nov-Apr','Temperate Maritime','111','Middle-earth landscapes with pristine wilderness, great walks, and volcanic terrain.','🇳🇿','["Milford Track","Routeburn Track","Tongariro Alpine Crossing","Abel Tasman Coast"]')
on conflict (id) do nothing;
