# ProGuard / R8 rules to keep Flutter and plugin entry points
# Keep Flutter classes
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugins.** { *; }
-keep class io.flutter.embedding.** { *; }

# Keep MapLibre and other reflection-heavy libraries
-keep class org.maplibre.** { *; }
-keep class com.mapbox.** { *; }

# Keep Supabase and Jackson/JSON serializers if used
-keep class io.supabase.** { *; }
-keep class com.fasterxml.** { *; }
-keep class kotlinx.serialization.** { *; }

# Keep Kotlin metadata
-keep class kotlin.Metadata { *; }

# Keep Firebase/Google Play services if present
-keep class com.google.** { *; }
-dontwarn com.google.**

# Do not obfuscate models generated by plugins (safe default)
-keepclassmembers class ** {
    @com.google.gson.annotations.SerializedName <fields>;
}
